isources:
  - ingress

domainFilters:
  - katralis.net

# upser-only allows only adding DNS records
# sync allows deletion
policy: sync
# Increase sync interval to ensure we are not spamming DNS server
# Default interval is 1 min
# Enable syncing on event to ensure changes and deployments propagate quickly
interval: 1h
triggerLoopOnEvent: true

registry: txt
txtOwnerId: k3s

extraArgs:
  # Only touch explicitly opted-in Ingresses
  - --annotation-filter=external-dns.kubernetes.io/enabled=true
  # Never manage A/AAAA records
  - --managed-record-types=CNAME
  - --managed-record-types=TXT
  # Using traefik for ingress  
  - --ingress-class=traefik
  # Set DNS Server with DNS Name, so that underlying IPs can change
  # While avoiding headaches
  - --rfc2136-host=dns01.katralis.net
  - --rfc2136-port=53
  - --rfc2136-zone=katralis.net
  # AXFR retrieves records and only updates if new records exist.
  # If AXFR is disabled, external-dns adds all records every time
  - --rfc2136-axfr
  - --rfc2136-tsig-secret-alg=hmac-sha256
  # Optional: Increase time interval between event and sync to avoid flooding server with requests
  # - --min-event-sync-interval=30s
  # Optional: Set time to cache DNS records for (avoids additional AXFR requests)
  # - --provider-cache-time=0s

env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
    valueFrom:
      secretKeyRef:
        name: rfc2136-keys
        key: rfc2136-tsig-keyname

  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: rfc2136-keys
        key: rfc2136-tsig-secret

provider:
  name: rfc2136
